import React, { useState, useReducer } from 'react'
import Head from 'next/head'
// Api
import { apiURL } from '../../lib/apiURL';
import { getPlaces } from '../../lib/apiCall';
// Components
import Navigation from '../../components/Navigation/Navigation';
import Sidebar from '../../components/Sidebar/Sidebar';
// Icons Material UI


export const getStaticPaths = async () => {
  const placesArray = await getPlaces(apiURL);

  const paths = placesArray.map((places) => {
    return {
      params: { id: places.id.toString() },
    };
  });

  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps = async (context) => {
  const id = context.params.id;
  const places = await getPlaces(apiURL + '/' + id);

  return {
    props: { places: places },
  };
};

function Edit(
  {places: {
    id, 
    Name, 
    Price, 
    About, 
    Location, 
    Rooms,
    Beds,
    ImgArray,
    Type,
    Type: {Hotel, Hostel, Cabin, Apartment},
    ImgArray: {ImgAlt, ImgUrl},
    Ratings,
    Ratings: {Star, Date, RatingsName, Message},
    Size, 
    Amenities: {
      Bathtub,
      Breakfast,
      Cleaning,
      CoffeeMachine,
      Dishwasher,
      Dryer,
      Fireplace,
      Gym,
      Heating,
      Iron,
      Laundry,
      Lift,
      Microwave,
      Parking,
      Pool,
      Refrigerator,
      Spa,
      TV,
      Washer,
      Wifi,
      },
    RoomDetails,
    RoomDetails: 
      {
        CheckIn, 
        CheckOut,
        Parties, 
        Pets,
        Rules,
        Smoking,
      }
    }
  }
) 
{
  const [values, setValues] = useState({
    id: '',
    Name: '',
    Price: '',
    About: '',
    Location: '',
    Rooms: '',
    Beds: '',
    ImgArray: '',
    ImgAlt: '',
    ImgUrl: '',
    Type: '',
    Hotel: '',
    Hostel: '',
    Cabin: '',
    Apartment: '',
    Star: '',
    Date: '',
    RatingsName: '',
    Message: '',
    Size: '',
    Bathtub: '',
    Breakfast: '',
    Cleaning: '',
    CoffeeMachine: '',
    Dishwasher: '',
    Dryer: '',
    Fireplace: '',
    Gym: '',
    Heating: '',
    Iron: '',
    Laundry: '',
    Lift: '',
    Microwave: '',
    Parking: '',
    Pool: '',
    Refrigerator: '',
    Spa: '',
    TV: '',
    Washer: '',
    Wifi: '',
    CheckIn: '',
    CheckOut: '',
    Parties: '',
    Pets: '',
    Rules: '',
    Smoking: '',
  });


  return (
    <>
      <Head>
        <title>Edit {Name}</title>
        NEEDED
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header id={id}>
        <Navigation id={id} />
        <Sidebar/>
      </header>
      <main>
        <h1>Edit {Name}</h1>
      </main>
    </>
  )
}

export default Edit;

// id: id,
// Name: Name,
// Price: Price,
// About: About,
// Location: Location,
// Rooms: Rooms,
// Beds: Beds,
// ImgArray: ImgArray,
// ImgAlt: ImgAlt,
// ImgUrl: ImgUrl,
// Type: Type,
// Hotel: Hotel,
// Hostel: Hostel,
// Cabin: Cabin,
// Apartment: Apartment,
// Star: Star,
// Date: Date,
// RatingsName: RatingsName,
// Message: Message,
// Size: Size,
// Bathtub: Bathtub,
// Breakfast: Breakfast,
// Cleaning: Cleaning,
// CoffeeMachine: CoffeeMachine,
// Dishwasher: Dishwasher,
// Dryer: Dryer,
// Fireplace: Fireplace,
// Gym: Gym,
// Heating: Heating,
// Iron: Iron,
// Laundry: Laundry,
// Lift: Lift,
// Microwave: Microwave,
// Parking: Parking,
// Pool: Pool,
// Refrigerator: Refrigerator,
// Spa: Spa,
// TV: TV,
// Washer: Washer,
// Wifi: Wifi,
// CheckIn: CheckIn,
// CheckOut: CheckOut,
// Parties: Parties,
// Pets: Pets,
// Rules: Rules,
// Smoking: Smoking,