// React / Headless
import Head from 'next/head'
// Components
import Navigation from '../components/Navigation/Navigation';
import Sidebar from '../components/Sidebar/Sidebar';
import HeroIndex from '../components/HeroIndex/HeroIndex';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navigation />
        <Sidebar/>
      </header>
      <main>
        <div className="hero-container">
          <HeroIndex />
        </div>
      </main>

      <footer>
      </footer>
    </>
  )
}
