import React from 'react'
import Head from 'next/head'
// Components
import Navigation from '../components/Navigation/Navigation';

function Stay() {
  return (
    <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <header>
      <Navigation />
    </header>

    <main>
      <p>This is a test</p>
    </main>

    <footer>
    </footer>
  </>
  )
}

export default Stay