import React from 'react'
import Head from 'next/head'
// Components
import Navigation from '../components/Navigation/Navigation';
import Sidebar from '../components/Sidebar/Sidebar';
import StaysHero from '../components/HeroStays/StaysHero';
import StaysSidebar from '../components/StaysSidebar/StaysSidebar';
import StaysHeading from '../components/StaysHeading/StaysHeading';
import StaysCards from '../components/StaysCards/StaysCards';

function Stay() {
  return (
    <>
     <Head>
        <title>Holidaze</title>
        NEEDED
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navigation />
        <Sidebar/>
      </header>
      <main>
        <StaysHero/>
        <StaysHeading/>
        <StaysSidebar/>
        <StaysCards/>
      </main>

      <footer>
      </footer>
  </>
  )
}

export default Stay