import React from 'react'
import Head from 'next/head'
// Components
import Navigation from '../components/Navigation/Navigation';
import Sidebar from '../components/Sidebar/Sidebar';
import StaysHero from '../components/HeroStays/StaysHero';
import StaysSidebar from '../components/StaysSidebar/StaysSidebar';
import StaysHeading from '../components/StaysHeading/StaysHeading';
import StaysCards from '../components/StaysCards/StaysCards';
// Axios
const axios = require('axios').default;

// API
export const getStaticProps = async () => {
  const res = await fetch("http://localhost:1337/places");
  const data = await res.json();

  return {
    props: { places: data },
  };
};

function Stay({places}) {
  console.log(places);
  
  return (
    <>
     <Head>
        <title>Holidaze</title>
        NEEDED
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navigation />
        <Sidebar/>
      </header>
      <main>
        <StaysHero/>
        <StaysHeading/>
        <StaysSidebar/>
        <div className="staysCards">
          {places.map((
            {
              id, 
              Name, 
              Price, 
              About, 
              Location, 
              Ratings,
              ImgArray,
              Size,
              Amenities,
            }
          ) =>  {
            return (
            <StaysCards 
              key={id}
              Name={Name}
              About={About}
              Price={Price}
              Location={Location}
              Ratings={Ratings}
              ImgArray={ImgArray}
              Size={Size}
              Amenities={Amenities}
            />
            );
            }
          )}
        </div>
        {/* <StaysCards/> */}
      </main>

      <footer>
      </footer>
  </>
  )
}

export default Stay